config/routes.rb
Bazar::Application.routes.draw do


  themes_for_rails

#  root :to => 'home#home'
  root :to => 'home#queesbazar'


  match '/noticias.rss' => 'noticias#rss'
  match '/actividades.rss' => 'actividades#rss'
  match '/actividades.rss' => 'actividades#rss'
  
  
  resources :favoritos
  resources :actividades

  resources :noticias
  resources :clusters
  resources :mensajes
  resources :gruposconfs
  resources :confs
  resources :roles_users
  resources :roles
  resources :user_sessions
  resources :ciudades
  resources :paises
  resources :password_resets
  
  # get 'login(.:format)' => 'user_sessions#new', :as => :login
  # post 'login(.:format)' => 'user_sessions#create', :as => :login
  # delete 'logout(.:format)' => 'user_sessions#destroy', :as => :logout
  
  resources :users
  
  match 'micuenta' => "user#edit",          :as => :micuenta
  match 'login' => "user_sessions#new",      :as => :login
  match 'logout' => "user_sessions#destroy", :as => :logout
  match '/registrarse' => "users#registrarse"
  match '/altaregistrarse' => "users#altaregistrarse"
  match '/home/micuenta/:id' => "home#micuenta", :constrants => { :id => /\d+/ }
  match '/home/actualizamicuenta/:id' => "home#actualizamicuenta", :constrants => { :id => /\d+/ } 
  
  match 'home' => "home#index"
  match '/home/bazares' => "home#bazares"
  match '/home/datos' => "home#datos"
  match '/home/open' => "home#open"
  match '/home/dashboardbazar' => "home#dashboardbazar"
  match '/home/busquedageneral' => "home#busquedageneral"
  match '/home/redirigebusqueda' => "home#redirigebusqueda"

  match '/home/ofertas/:tipo' => "home#ofertas"
  match '/home/fichaoferta/:bazar/:id' => "home#fichaoferta", :constrants => { :id => /\d+/ , :bazar => /\d+/ }
  match '/busqueda-oferta' => "home#busquedaoferta"
  match '/home/ofertadatosgenerales/:bazar/:id' => "home#ofertadatosgenerales", :constrants => { :id => /\d+/ , :bazar => /\d+/ }
  match '/home/actofertadatosgenerales/:bazar/:id' => "home#actofertadatosgenerales", :constrants => { :id => /\d+/ , :bazar => /\d+/ }
  match '/home/crearoferta/:bazar/:id' => "home#crearoferta", :constrants => { :id => /\d+/ , :bazar => /\d+/ }
  
  match '/home/empresas/' => "home#empresas"
  match '/home/fichaempresa/:bazar/:id' => "home#fichaempresa", :constrants => { :id => /\d+/ , :bazar => /\d+/ }
  match '/busqueda-empresa' => "home#busquedaempresa"
  match '/home/empresadatosgenerales/:bazar/:id' => "home#empresadatosgenerales", :constrants => { :id => /\d+/ , :bazar => /\d+/ }
  match '/home/empresadatosgenerales2/:bazar/:id' => "home#empresadatosgenerales2", :constrants => { :id => /\d+/ , :bazar => /\d+/ }
  match '/home/actempresadatosgenerales/:bazar/:id' => "home#actempresadatosgenerales", :constrants => { :id => /\d+/ , :bazar => /\d+/ }
  match '/home/crearimagenempresa' => "home#crearimagenempresa"
  match '/home/delempresaimagen/:empresa/:id' => "home#delempresaimagen", :constrants => { :id => /\d+/ , :empresa => /\d+/ }
  match '/home/empresasestimadas' => "home#empresasestimadas"
  match '/home/filtraresultadosempresas/:resu/:tipo' => "home#filtraresultadosempresas", :constrants => { :resu => /\d+/ , :tipo => /\s+/ }
  match '/home/addsede/:id' => "home#addsede", :constrants => { :id => /\d+/ }
  match '/home/grabasede/' => "home#grabasede"
  match '/home/delsede/:empresa/:id' => "home#delsede", :constrants => { :empresa => /\d+/, :id => /\d+/ }
  match '/home/cambiarlogo' => "home#cambiarlogo"

  
  match '/home/favoritos/' => "home#favoritos"
  match '/home/delfav/:bazar/:id' => "home#delfav", :constrants => { :id => /\d+/ , :bazar => /\d+/ }
  match '/home/addfav/:bazar/:id' => "home#addfav", :constrants => { :id => /\d+/ , :bazar => /\d+/ }
  match '/home/delofefav/:bazar/:id/:class' => "home#delofefav", :constrants => { :id => /\d+/ , :bazar => /\d+/ }
  match '/home/addofefav/:bazar/:id/:class' => "home#addofefav", :constrants => { :id => /\d+/ , :bazar => /\d+/ }
  match '/home/crearimagenoferta/:id/:empresa' => "home#crearimagenoferta", :constrants => { :id => /\d+/ , :empresa => /\d+/ }
  match '/home/delofertaimagen/:oferta/:id' => "home#delofertaimagen", :constrants => { :id => /\d+/ , :oferta => /\d+/ }
  match '/home/editaroferta/:oferta/:id' => "home#editaroferta", :constrants => { :id => /\d+/ , :oferta => /\d+/ }
  match '/home/imagenesoferta/:oferta' => "home#imagenesoferta", :constrants => {:oferta => /\d+/ }
  match '/home/subirimagenoferta/:oferta' =>  "home#subirimagenoferta", :constrants => {:oferta => /\d+/ }
  match '/home/cancelaroferta/:oferta' =>  "home#cancelaroferta", :constrants => {:oferta => /\d+/ }
  match '/home/publicaroferta/:oferta' =>  "home#publicaroferta", :constrants => {:oferta => /\d+/ }
  match '/home/filtraresultadosofertas/:resu/:tipo' => "home#filtraresultadosofertas", :constrants => { :resu => /\d+/ , :tipo => /\s+/ }
  
  match '/home/test/' => "home#test"
  match '/home/editarcorreo/:bazar/:id' =>  "home#editarcorreo", :constrants => {:bazar => /\d+/ , :id => /\d+/ }
  match '/home/enviarcorreo/:id' =>  "home#enviarcorreo", :constrants => {:id => /\d+/ }

  match '/home/rating/:bazar/:id/:valor' => "home#rating", :constrants => {:bazar => /\d+/ , :id => /\d+/, :valor => /\d+/}
  match '/home/ficharating/:bazar/:id/:valor' => "home#ficharating", :constrants => {:bazar => /\d+/ , :id => /\d+/, :valor => /\d+/}

  match '/mensajes/leido/:id' => "mensajes#leido", :constrants => { :id => /\d+/ }
  match '/mensajeremoto' => "mensajes#mensajeremoto"
  match "/mensaje/dashboard" => "mensajes#dashboard"
  match '/notificacion' => 'mensajes#notificacion', :as => :notificacion
  match '/enviarnotificacion' => 'mensajes#enviarnotificacion', :as => :enviarnotificacion

  match 'busquedaciudades' => 'ciudades#busqueda', :as => :busquedaciudades
  match '/clusters/activar/:id' => 'clusters#activar', :constrants => { :id => /\d+/ }, :as => :activar_cluster
  match '/updateinfo' => 'clusters#updateinfo', :as => :updateinfo
  match "/actividad/dashboard" => "actividades#dashboard"
  
  match "/favorito/addfav" => "favoritos#addfav"
  match "/favorito/delfav" => "favoritos#delfav"  
  match "/favorito/dashboard" => "favoritos#dashboard"

  match "/busquedapaises" => "paises#busqueda"
  
  match "/avisos/dashboard" => 'home#avisos'
  
  scope '/translate' do
    match '/translate_list', :to => 'translate#index'
    match '/translate', :to => 'translate#translate'
    match '/translate_reload', :to => 'translate#reload', :as => 'translate_reload'
  end

# API routes

 
  match '/api/index' => 'api#index'
  match '/api/info' => 'api#info'
  match '/api/empresas' => 'api#empresas'
  match '/api/perfiles' => 'api#perfiles'
  match '/api/paises' => 'api#paises'
  match '/api/infoempresa(.:format)/:id' => "api#infoempresa", :constrants => { :id => /\d+/ }
  match '/api/infooferta(.:format)/:id' => "api#infooferta", :constrants => { :id => /\d+/ }
  match '/api/buscaempresas' => 'api#buscaempresas'
  
  match '/api/ejemplos' => 'api#ejemplos'
  match '/api/ejemploinfo' => 'api#ejemploinfo'
  match '/api/ejemploempresas' => 'api#ejemploempresas'
  match '/api/ejemploinfoempresa' => 'api#ejemploinfoempresa'
  match '/api/ejemploinfooferta' => 'api#ejemploinfooferta'  
  match '/api/ejemploperfiles' => 'api#ejemploperfiles'
  match '/api/ejemplopaises' => 'api#ejemplopaises'


#    scope '/translate' do
#      match '/translate_list', :to => 'translate#index'
#      match '/translate', :to => 'translate#translate'
#      match '/translate_reload', :to => 'translate#reload', :as => 'translate_reload'
#    end
#  
#   Translate::Routes.translation_ui(map) if RAILS_ENV != "production"
  
  
end
Bazar::Application.routes.draw do


  themes_for_rails

#  root :to => 'home#home'
  root :to => 'home#queesbazar'


  match '/noticias.rss' => 'noticias#rss'
  match '/actividades.rss' => 'actividades#rss'
  match '/actividades.rss' => 'actividades#rss'
  
  
  resources :favoritos
  resources :actividades

  resources :noticias
  resources :clusters
  resources :mensajes
  resources :gruposconfs
  resources :confs
  resources :roles_users
  resources :roles
  resources :user_sessions
  resources :ciudades
  resources :paises
  resources :password_resets
  
  # get 'login(.:format)' => 'user_sessions#new', :as => :login
  # post 'login(.:format)' => 'user_sessions#create', :as => :login
  # delete 'logout(.:format)' => 'user_sessions#destroy', :as => :logout
  
  resources :users
  
  match 'micuenta' => "user#edit",          :as => :micuenta
  match 'login' => "user_sessions#new",      :as => :login # "user_sessions#new"
  match 'logout' => "user_sessions#destroy", :as => :logout
  match '/registrarse' => "users#registrarse"
  match '/altaregistrarse' => "users#altaregistrarse"
  
  match 'home' => "home#index"
  match '/home/bazares' => "home#queesbazar"
  match '/home/datos' => "home#queesbazar" # "home#datos"
  match '/home/open' => "home#open"
  match '/home/dashboardbazar' => "home#dashboardbazar"
  match '/home/busquedageneral' => "home#busquedageneral"
  match '/home/redirigebusqueda' => "home#redirigebusqueda"

  match '/home/ofertas/:tipo' => "home#ofertas"
  match '/home/fichaoferta/:bazar/:id' => "home#fichaoferta", :constrants => { :id => /\d+/ , :bazar => /\d+/ }
  match '/busqueda-oferta' => "home#busquedaoferta"
  match '/home/ofertadatosgenerales/:bazar/:id' => "home#ofertadatosgenerales", :constrants => { :id => /\d+/ , :bazar => /\d+/ }
  match '/home/actofertadatosgenerales/:bazar/:id' => "home#actofertadatosgenerales", :constrants => { :id => /\d+/ , :bazar => /\d+/ }
  match '/home/crearoferta/:bazar/:id' => "home#crearoferta", :constrants => { :id => /\d+/ , :bazar => /\d+/ }
  
  match '/home/empresas/' => "home#empresas"
  match '/home/fichaempresa/:bazar/:id' => "home#fichaempresa", :constrants => { :id => /\d+/ , :bazar => /\d+/ }
  match '/busqueda-empresa' => "home#busquedaempresa"

app/views/layouts/bazar.html.erb
<!DOCTYPE html>
<html>
  <% cache "header", {:expires_in => 1.hours.to_i} do %>
  <head>
	<meta name="description" content="proyecto bazar, garum fundatio, agilizando mercados <%= h BZ_param("Titular") %>, <%= h BZ_param("Subtitular") %>" /> 
	<meta name="keywords" content="proyecto bazar, garum, garum fundatio, marketplace, agilizando mercados, <%= h BZ_param("Titular") %>, <%= h BZ_param("Subtitular") %>" /> 
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	
	<link rel="icon" href="/images/favicon.ico" type="image/x-icon" />
	<link rel="shortcut icon" href="/images/favicon.ico" type="image/x-icon" />
	
	<title><%= h BZ_param("Titular") %></title>
	<%= javascript_include_tag :defaults %>
	<%= javascript_include_tag "jquery-ui.js" %>
	<%= javascript_include_tag "jquery.cycle.all.min.js" %>

	<%= stylesheet_link_tag("bazar") %>

	
	<%= csrf_meta_tag %>
	
	<% end %>

	<% if BZ_param("BazarId").to_i == 2 %>
	<script type="text/javascript">

	  var _gaq = _gaq || [];
  	  _gaq.push(['_setAccount', 'UA-215887-21']);
	  _gaq.push(['_trackPageview']);

	  (function() {
	    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
	    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
	    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
	  })();

	</script>
	<% end %>
	
	
  </head>
	
		<% if !current_user.nil? %>
			<body class="logueado"><!-- si usuario logueado -->
			<% if !current_user_is_admin %>
				<body class="admin"><!-- si usuario administrador -->
			<% end %>
		<% else %>
			<body class="anonimo"><!-- si es anónimo -->
		<% end %>

	
   <div class="container">

	  <div id="header">
	  
	  <div id="logo"></div>
	  <div id="nombresitio">
		      <h1 id="title"><a
              <% if !current_user.nil? %>
                 href="/home"
              <% else %>
                 href="/"
              <% end %>
              ><%= h BZ_param("Titular") %></a>
              </h1>
	          <h2 id="slogan"><%= h BZ_param("Subtitular") %></h2>
		</div>
	  
      <% if current_user.nil? %>
			<div id="socioenlaces">
				<ul>
					<li><a href="/home/bazares"><%=t(:text_mercado)%></a></li>
					<li><a href="/home/datos"><%=t(:text_sociologia)%></a></li>
					<li><a href="http://garumfundatio.org/faq-bazar"><%=t(:text_f_a_q)%></a></li>
					<li><a class="login-link" href="/login"><%=t(:text_entrar)%></a></li>
				</ul>
			</div>      
      
      <% end %>
      
      	  </div>

      <% if !current_user.nil? %>
			<div id="nav-usuario">
				<div class="user-links">
				<%= link_to current_user.login,  edit_user_path(current_user.id), :class => 'user-link' %>
				<%= link_to(image_tag('icono-logout.png'),  "/logout", :class => 'logout-link', :title => 'Cerrar Sesión') %>
				</div>
				<div class="user-messages">
				<%= link_to(image_tag('notificacion.png'),  "/mensajes?tipo=N", :class => 'notif-link', :title => 'Notificaciones sin leer') %>
				<strong><%= Mensaje.notificacionessinleer(current_user.id).count -%></strong>

				<%= link_to(image_tag('email.png'),  "/mensajes?tipo=M", :class => 'msgs-link', :title => 'Mensajes sin leer') %>
				<strong><%= Mensaje.mensajessinleer(current_user.id).count -%></strong>

				</div>
				<div class="nav-site">
                <%= link_to(image_tag('icono-home.png'), "/home", :class => 'home-link', :title => 'Página Principal') %>
                <%= link_to(image_tag('icono-usuario.png'), edit_user_path(current_user.id), :class => 'account-link', :title => 'Mi Cuenta') %>
                <%= link_to(image_tag('group.png'), edit_bazarcms_empresa_path(current_user.id), :class => 'empresa-link', :title => 'Mi Empresa') %>
		<%= link_to(image_tag('favorito.png'), "/favoritos", :class => 'favoritos-link', :title => 'Ver Empresas, ofertas y demandas que sigue') %>
                <%= link_to(image_tag('icono-historial.png'), bazarcms_empresasconsultas_path, :class => 'historial-link', :title => 'Historial de Consultas Realizadas') %>
                <%= link_to(image_tag('add.png'), "/bazarcms/publicaroferta", :class => 'crear-oferta-link', :title => 'Crear Oferta/Demanda') %>
                <% if current_user_is_admin || current_user_is_dinamizador %>
                    <%= link_to(image_tag('icono-admin.png'), "#", :class => 'administracion-link', :title => 'Administración') %>
                <% end %>
                </div>
            </div>
      <% end %>
	  
	  <% if current_user_is_admin || current_user_is_dinamizador %>
        <div id="nav-admin-container">
             <ul id="nav-admin">
			  <% if current_user_is_admin %>	
                 <li><a href="#"><%=t(:text_administrador)%></a>
		            <ul>
					  <li><%= link_to t(:label_usuarios), users_path %> </li>
					  <li><%= link_to "Configuración del Sistema", confs_path %> </li>
					  <li><%= link_to "Gestión Bazares", clusters_path %> </li>
					  <li><%= link_to t(:label_notificacion_a_usuarios), '/notificacion?tipo=N' %> </li>
					  <li><%= link_to "Actualización Información", '/updateinfo' %> </li>
		            </ul>
                 </li>
			<% end %>
		  	<% if current_user_is_dinamizador %>
                 <li><a href="#"><%=t(:text_dinamizador)%></a>
		            <ul class="links">
						<li><%= link_to t(:label_usuarios), users_path %> </li>
					    <li><%= link_to t(:label_mailing_a_usuarios), '/notificacion?tipo=M' %> </li>
					    <li><%= link_to t(:label_noticias), noticias_path %> </li>
		            </ul>
                 </li>
            <% end %>
 			</ul>
        </div><!-- /#nav-admin-container -->
        
        <script>
            $('.administracion-link').click(function() {
                $('#nav-admin-container').toggle();
            });
        </script>
      <% end %>
 
	  <div id="content" class="span-24 last">	
			<div class="body">

			<div id="contenido" >
				<%= content_for?(:bazarcontent) ? yield(:bazarcontent) : yield %>
			</div>
			<div id="sidebar" style="display:none" >
	        <ul id="sidebar-items">
			
				<% if current_user.nil? %>
				<h3><%=t(:text_rss)%></h3>
				<ul class="links">
					<li><%= image_tag('feed.png')-%> <%= link_to("Noticias", "/noticias.rss") -%></li>
				</ul>
			
				<% end %>

			  <li>
							<% if !current_user.nil? %>
							<ul id="user-menu" class="links">
								<li class="user-links">
								<%= link_to current_user.login,  edit_user_path(current_user.id), :class => 'user-link' %>
								<%= link_to(image_tag('icono-logout.png'),  "/logout", :class => 'logout-link', :title => 'Cerrar Sesión') %>
								</li>
								<% cache "mensajesconta#{current_user.id}", {:expires_in => 5.minutes.to_i} do %>
								<li class="user-messages">
								<%= link_to(image_tag('notificacion.png'),  "/mensajes?tipo=N", :class => 'notif-link', :title => 'Notificaciones') %>
								(<%= Mensaje.notificacionessinleer(current_user.id).count -%>/<%=  Mensaje.notificacionestotal(current_user.id).count -%>) 
								
								<%= link_to(image_tag('email.png'),  "/mensajes?tipo=M", :class => 'msgs-link', :title => 'Mensajes') %>
								(<%= Mensaje.mensajessinleer(current_user.id).count -%>/<%=  Mensaje.mensajestotal(current_user.id).count -%>) 

								</li>
								<% end %>
                            </ul>
							<% end %>
		          </li>	
	          <li>

	        </ul>
	     </div>	
			</div>
			
			
			
			
	  </div>

		<div id="footer">
	    		<a href="http://garumfundatio.org/bazar">Bazar</a> es software libre desarrollado por <a href="http://garumfundatio.org" style="text-decoration: none"><%=t(:text_garum_fundatio)%></a> bajo los términos de la licencia GPL v3.
		</div> <!-- fin footer-->

	

  </div> <!-- fin container -->



  </body>
</html>